apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tawazn-mysql-pv-claim
  labels:
    name: DohaQadi
    app: tawazun
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: standard
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      app: tawazun
     