apiVersion: v1
kind: PersistentVolume
metadata:
  name: tawazn-mysql-pv
  labels:
    app: tawazun
    name: DohaQadi
    type: local
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: "/tawazun/pv" 
  