apiVersion: v1
kind: Service
metadata:
  name: tawazun-mysql-service
  labels:
    name: DohaQadi
    app: tawazun-mysql-service
spec:
  selector:
    app: mysql-tawazun
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3306 